---

language: go

go:
  - '1.13.4'

before_install:
  - go get github.com/mattn/goveralls

install:
  - GOOS=linux GOARCH=amd64 go build -o beancounter-${TRAVIS_TAG}-linux-amd64
  - GOOS=darwin GOARCH=amd64 go build -o beancounter-${TRAVIS_TAG}-osx-amd64
  - GOOS=windows GOARCH=amd64 go build -o beancounter-${TRAVIS_TAG}-windows-amd64.exe

script:
  - go test -v ./... -coverprofile coverage.out

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile coverage.out -service=travis-ci
